language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
# command to install dependencies
install: "pip install -r dev_requirements.txt coveralls"
# command to run tests
script:
  - flake8 .
  - py.test tests
after_success:
  - coveralls